[profile.default]
solc_version = '0.8.23'
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
evm_version = 'paris'
optimizer = true
optimizer_runs = 200
ignored_error_codes = []
