export default {
  NONE: 0,
  CHAINLINK: 1,
  PYTH: 2,
  PRICE_DEVIATION_CIRCUIT_BREAKER: 3,
  PRICE_DEVIATION_SAME_ORACLE_CIRCUIT_BREAKER: 4,
  STALENESS_CIRCUIT_BREAKER: 5,
  SAME_ORACLE_BREAKER: 6,
  CONSTANT: 7,
  REDUCER: 8,
  EXTERNAL: 9,
};
